# Generated by Django 4.2.3 on 2023-08-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutismAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfants',
            name='EnfantEthmicity',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='enfants',
            name='EnfantFamelyMsd',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AddField(
            model_name='enfants',
            name='EnfantJaundice',
            field=models.CharField(default='Yes', max_length=100),
        ),
        migrations.AddField(
            model_name='testsautisme',
            name='TestIdEnfant',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='testsautisme',
            name='TestScore',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
