# Generated by Django 4.2.3 on 2023-08-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutismAPP', '0002_enfants_enfantethmicity_enfants_enfantfamelymsd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfants',
            name='EnfantAutiste',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='testsautisme',
            name='TestQ1',
            field=models.CharField(max_length=10),
        ),
    ]
